version: '3.9'
services:
  postgres-sandbox:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=pojo_database
      - POSTGRES_USER=pojo_user_database
      - POSTGRES_PASSWORD=kguITyf41pkYBKeKo7ZIRfdTV2vOKKka
    ports:
      - "54333:5432"
    healthcheck:
      test: pg_isready -h dpg-ch5qvrks3fvuoba7f91g-a -u $$POSTGRES_USER -p $$POSTGRES_DB
      timeout: 30s
      retries: 5

  backend:
    build: .
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
    depends_on:
      - postgres-sandbox
    environment:
      - ENVIRONMENT=dev
    restart: always
    ports:
      - "3510:3500"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "3570:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
    depends_on:
      - backend
      - postgres-sandbox

  grafana:
    image: grafana/grafana-oss:9.3.6
    ports:
      - "3000:3000"
    user: "472"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    depends_on:
      - backend
      - prometheus
      - postgres-sandbox